### ISSUE TITLE
Skip documents with identical title and text in import menu not working

### ISSUE THREAD

**Issue by TimHenrichsen** [leifeld/dna#214]
When you activate the “skip documents with identical title and text” option in the “Import from DNA database” menu, no documents are imported.

**Comment by leifeld** [comment]
Log file in XML format:

```xml
<log>
  <version>3.0.0 alpha 2</version>
  <date>2022-01-17</date>
  <events>
    <event>
      <date>19.01.2022 15:41:37.308</date>
      <priority>3</priority>
      <coder>1</coder>
      <summary>[SQL] Failed to import data from other database.</summary>
      <details>Attempted importing data from another database, but the import failed. The transaction has been rolled back, and no changes have been written to the currently open database. Check the exception message stack for details.</details>
      <stackLog>logger.LogEvent&#xd;
	at gui.Importer$ImportWorker.run(Importer.java:1711)&#xd;
	at java.lang.Thread.run(Unknown Source)&#xd;
</stackLog>
      <stackException>java.sql.SQLException: column 0 out of bounds [1,1]&#xd;
	at org.sqlite.core.CoreResultSet.checkCol(CoreResultSet.java:91)&#xd;
	at org.sqlite.core.CoreResultSet.markCol(CoreResultSet.java:104)&#xd;
	at org.sqlite.jdbc3.JDBC3ResultSet.getInt(JDBC3ResultSet.java:393)&#xd;
	at gui.Importer$ImportWorker.run(Importer.java:1525)&#xd;
	at java.lang.Thread.run(Unknown Source)&#xd;
</stackException>
    </event>
    <event>
      <date>19.01.2022 15:42:14.140</date>
      <priority>3</priority>
      <coder>1</coder>
      <summary>[SQL] Failed to import data from other database.</summary>
      <details>Attempted importing data from another database, but the import failed. The transaction has been rolled back, and no changes have been written to the currently open database. Check the exception message stack for details.</details>
      <stackLog>logger.LogEvent&#xd;
	at gui.Importer$ImportWorker.run(Importer.java:1711)&#xd;
	at java.lang.Thread.run(Unknown Source)&#xd;
</stackLog>
      <stackException>java.sql.SQLException: column 0 out of bounds [1,1]&#xd;
	at org.sqlite.core.CoreResultSet.checkCol(CoreResultSet.java:91)&#xd;
	at org.sqlite.core.CoreResultSet.markCol(CoreResultSet.java:104)&#xd;
	at org.sqlite.jdbc3.JDBC3ResultSet.getInt(JDBC3ResultSet.java:393)&#xd;
	at gui.Importer$ImportWorker.run(Importer.java:1525)&#xd;
	at java.lang.Thread.run(Unknown Source)&#xd;
</stackException>
    </event>
  </events>
</log>
```

**Comment by leifeld** [comment]
Fixed in https://github.com/leifeld/dna/commit/6d36da9081a39ec1111a5024d33a2a72b0e83392.
