### ISSUE TITLE
Problem with import of 2.0 databases with coded statements by multiple coders

### ISSUE THREAD

**Issue by TimHenrichsen** [leifeld/dna#217]
I tried to import a DNA 2.0 database with several coded statements by multiple coders. Before doing that, I matched the coder profiles of the target 3.0. database with the source 2.0. database, so that the imported statements can be assigned to the individual coders. The documents and statements can be successfully imported but the coded statements are not visible in the documents. Luckily, the statements are visible once you close and re-open DNA but perhaps this might still be interesting to have a look at.

I also received the following message in the terminal:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "model.CoderRelation.isViewStatements()" because the return value of "java.util.HashMap.get(Object)" is null
        at gui.TextPanel.paintStatements(TextPanel.java:143)
        at gui.TextPanel.setContents(TextPanel.java:118)
        at gui.MainWindow.changedDocumentTableSelection(MainWindow.java:1283)
        at gui.MainWindow.access$9(MainWindow.java:1241)
        at gui.MainWindow$3.valueChanged(MainWindow.java:409)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:191)
        at java.desktop/javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:728)
        at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.setValueIsAdjusting(BasicTableUI.java:992)
        at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(BasicTableUI.java:1205)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6382)
        at java.desktop/java.awt.Container.processEvent(Container.java:2264)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by leifeld** [comment]
Thanks, I'll have a look. Can you please send me a database with which I can reproduce the error? It does not seem to happen with my old databases.

**Comment by leifeld** [comment]
@TimHenrichsen I have tried again but can't seem to reproduce the problem. Any further instructions for reproducing the error would be appreciated. Thx.

**Comment by TimHenrichsen** [comment]
I also couldn't reproduce the problem just now. But I'll do another check tomorrow.

**Comment by TimHenrichsen** [comment]
Couldn't reproduce the problem anymore. I'll close the issue.
