### ISSUE TITLE
Exception after editing actor attributes and closing the file without saving

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#22]
__What steps will reproduce the problem?__
    1. Open a DNA file
    2. Change the actor type of some organizations
    3. Save the file
    4. Close the DNA file

__What is the expected output? What do you see instead?__
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException at dna.ActorManager$6.valueChanged(ActorManager.java:234) at javax.swing.JList.fireSelectionValueChanged(JList.java:1782) at javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1796) at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184) at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164) at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211) at javax.swing.DefaultListSelectionModel.removeIndexInterval(DefaultListSelectionModel.java:677) at javax.swing.plaf.basic.BasicListUI$Handler.intervalRemoved(BasicListUI.java:2597) at javax.swing.AbstractListModel.fireIntervalRemoved(AbstractListModel.java:178) at javax.swing.DefaultListModel.removeAllElements(DefaultListModel.java:402) at dna.DnaContainer.clear(DnaContainer.java:35) at dna.Dna.clearSpace(Dna.java:1019) at dna.Dna.closeDnaFile(Dna.java:1007) at dna.Dna.access$1(Dna.java:989) at dna.Dna$14.actionPerformed(Dna.java:1290)

__What version of the product are you using? On what operating system?__
1.25, Ubuntu 10.10

First submitted: 2011-03-22

**Comment by leifeld** [comment]
Outdated. Working on a new version anyway.
