### ISSUE TITLE
Failed to retrieve statements in MySQL connection

### ISSUE THREAD

**Issue by TimHenrichsen** [leifeld/dna#220]
With the DNA 3.0 alpha 4 version, statements are not retrieved and the statement list remains empty. I also receive the following warning message:

```xml
<log>
  <version>3.0.0 alpha 4</version>
  <date>2022-01-21</date>
  <events>
    <event>
      <date>21.01.2022 10:31:59.210</date>
      <priority>2</priority>
      <coder>1</coder>
      <summary>[SQL] Failed to retrieve statements.</summary>
      <details>Attempted to retrieve all statements from the database, but something went wrong. You should double-check if the statements are all shown!</details>
      <stackLog>logger.LogEvent&#xd;
	at gui.MainWindow$StatementTableRefreshWorker.doInBackground(MainWindow.java:1187)&#xd;
	at gui.MainWindow$StatementTableRefreshWorker.doInBackground(MainWindow.java:1)&#xd;
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)&#xd;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xd;
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)&#xd;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)&#xd;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)&#xd;
	at java.base/java.lang.Thread.run(Thread.java:831)&#xd;
</stackLog>
      <stackException>java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near &apos;TEXT) FROM DATABOOLEAN INNER JOIN VARIABLES ON VARIABLES.ID = DATABOOLEAN.Variab&apos; at line 1&#xd;
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)&#xd;
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)&#xd;
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)&#xd;
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)&#xd;
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)&#xd;
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)&#xd;
	at gui.MainWindow$StatementTableRefreshWorker.doInBackground(MainWindow.java:1165)&#xd;
	at gui.MainWindow$StatementTableRefreshWorker.doInBackground(MainWindow.java:1)&#xd;
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)&#xd;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xd;
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)&#xd;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)&#xd;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)&#xd;
	at java.base/java.lang.Thread.run(Thread.java:831)&#xd;
</stackException>
    </event>
  </events>
</log>
```

**Comment by leifeld** [comment]
Fixed in 1aa5783598759633a13ab7962fba45493ae6bbcd.
