### ISSUE TITLE
Add new coder throws error in DNA 3.0.2

### ISSUE THREAD

**Issue by TimHenrichsen** [leifeld/dna#228]
Adding a new coder is not possible with the new update. Here's the error-log:
```xml
<log>
  <version>3.0.2</version>
  <date>2022-02-14</date>
  <events>
    <event>
      <date>15.02.2022 09:18:29.215</date>
      <priority>3</priority>
      <coder>1</coder>
      <summary>Uncaught exception.</summary>
      <details>An uncaught exception occurred. This is most likely a bug. Please open a new issue at https://github.com/leifeld/dna/issues/ and paste the log event stack trace and the exception stack trace there as part of your error description, along with details of what happened and under what circumstances. Thank you.</details>
      <stackLog>logger.LogEvent&#xd;
	at dna.Dna$DefaultExceptionHandler.uncaughtException(Dna.java:61)&#xd;
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1074)&#xd;
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1069)&#xd;
	at java.desktop/java.awt.EventDispatchThread.processException(EventDispatchThread.java:222)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:214)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)&#xd;
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)&#xd;
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)&#xd;
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)&#xd;
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)&#xd;
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)&#xd;
	at java.desktop/java.awt.Dialog.show(Dialog.java:1079)&#xd;
	at java.desktop/java.awt.Component.show(Component.java:1720)&#xd;
	at java.desktop/java.awt.Component.setVisible(Component.java:1667)&#xd;
	at java.desktop/java.awt.Window.setVisible(Window.java:1032)&#xd;
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1014)&#xd;
	at gui.CoderManager.&lt;init&gt;(CoderManager.java:539)&#xd;
	at gui.MainWindow$ActionCoderManager.actionPerformed(MainWindow.java:1891)&#xd;
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)&#xd;
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)&#xd;
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)&#xd;
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)&#xd;
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)&#xd;
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1022)&#xd;
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1066)&#xd;
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)&#xd;
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)&#xd;
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)&#xd;
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)&#xd;
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)&#xd;
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)&#xd;
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)&#xd;
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)&#xd;
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)&#xd;
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)&#xd;
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)&#xd;
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)&#xd;
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)&#xd;
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)&#xd;
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)&#xd;
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)&#xd;
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)&#xd;
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)&#xd;
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)&#xd;
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)&#xd;
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)&#xd;
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)&#xd;
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)&#xd;
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)&#xd;
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)&#xd;
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)&#xd;
</stackLog>
      <stackException>java.lang.ClassCastException: class javax.swing.SwingUtilities$SharedOwnerFrame cannot be cast to class javax.swing.JFrame (javax.swing.SwingUtilities$SharedOwnerFrame and javax.swing.JFrame are in module java.desktop of loader &apos;bootstrap&apos;)&#xd;
	at gui.CoderManager$7.actionPerformed(CoderManager.java:464)&#xd;
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)&#xd;
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)&#xd;
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)&#xd;
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)&#xd;
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)&#xd;
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)&#xd;
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)&#xd;
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)&#xd;
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)&#xd;
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)&#xd;
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)&#xd;
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)&#xd;
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)&#xd;
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)&#xd;
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)&#xd;
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)&#xd;
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)&#xd;
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)&#xd;
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)&#xd;
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)&#xd;
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)&#xd;
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)&#xd;
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)&#xd;
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)&#xd;
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)&#xd;
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)&#xd;
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)&#xd;
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)&#xd;
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)&#xd;
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)&#xd;
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)&#xd;
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)&#xd;
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)&#xd;
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)&#xd;
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)&#xd;
	at java.desktop/java.awt.Dialog.show(Dialog.java:1079)&#xd;
	at java.desktop/java.awt.Component.show(Component.java:1720)&#xd;
	at java.desktop/java.awt.Component.setVisible(Component.java:1667)&#xd;
	at java.desktop/java.awt.Window.setVisible(Window.java:1032)&#xd;
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1014)&#xd;
	at gui.CoderManager.&lt;init&gt;(CoderManager.java:539)&#xd;
	at gui.MainWindow$ActionCoderManager.actionPerformed(MainWindow.java:1891)&#xd;
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)&#xd;
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)&#xd;
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)&#xd;
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)&#xd;
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)&#xd;
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1022)&#xd;
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1066)&#xd;
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)&#xd;
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)&#xd;
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)&#xd;
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)&#xd;
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)&#xd;
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)&#xd;
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)&#xd;
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)&#xd;
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)&#xd;
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)&#xd;
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)&#xd;
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)&#xd;
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)&#xd;
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)&#xd;
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)&#xd;
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)&#xd;
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)&#xd;
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)&#xd;
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)&#xd;
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)&#xd;
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)&#xd;
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)&#xd;
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)&#xd;
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)&#xd;
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)&#xd;
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)&#xd;
</stackException>
    </event>
  </events>
</log>
```

**Comment by leifeld** [comment]
Thanks, I'm on it! Will send you a new version soon.
