### ISSUE TITLE
Can't open SQLite Database since working on it yesterday, DNA version: 2.0 beta 25 (2019-09-08), Java version: 1.8.0_321, Operating system: Windows 10 10.0

### ISSUE THREAD

**Issue by AkselSB** [leifeld/dna#232]
Was working on this database yesterday and now I cannot open it. When specifying the path in rDNA, it opens a blank gui. When opening the database manually, it throws the following error code (below)

I've tried moving the database to the desktop but that hasn't worked either.  

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at dna.SqlConnection.getAllData(SqlConnection.java:249)
	at dna.OpenDatabaseDialog.loadDataAndDispose(OpenDatabaseDialog.java:288)
	at dna.OpenDatabaseDialog$3.actionPerformed(OpenDatabaseDialog.java:143)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at dna.OpenDatabaseDialog.<init>(OpenDatabaseDialog.java:283)
	at dna.Gui$MenuBar$2.actionPerformed(Gui.java:302)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by leifeld** [comment]
If you are willing to send the database to me by email, I'd be happy to look into the problem. It's hard to diagnose with these error codes alone. You'll find my contact details on my [homepage](https://www.philipleifeld.com/contact/).

**Comment by AkselSB** [comment]
I've sent the database via email. 

I've both tried to open the database with DB Browser for SQLite (which worked meaning it's not corrupted) and I've tried to create a new database from the same working directory (which also worked, so it's not the path either).

**Comment by leifeld** [comment]
Thanks for sending the file. It looks like this is a bug in the DNA 2.0 code base. It's weird because it has never been reported before, and I have never experienced it. I have checked the database itself, and it seems to be intact. In fact, I was able to import it without any problems into the new DNA 3.0, so the data seem to be fine.

I am not planning to fix any errors in the old version, DNA 2.0, but instead focus on getting the new version ready for productive use. The coding interface is already working well, but there is no network export yet and rDNA is not functional at the moment with DNA 3.0. The recoding functions are also still a bit limited. I am planning to have the complete network export and the recoding functions re-implemented within the next month, but rDNA functionality will be a longer project, and I hope to have that re-implemented in late summer/early autumn. If you don't need rDNA for now and can do without the network export for a few weeks, then I would be happy to share a link to DNA 3.0 with you, and you can use that for coding from now on. Let me know what you think and if you want to give it a try and see how you get on with it.

Alternatively, you could try to create a new database in DNA 2.0 and try to import the data from your current database into that new database within DNA 2.0. I don't know if it fixes the problem, but it may be worth a try.

**Comment by AkselSB** [comment]
Thank you for looking into it! I don't think I have the time to wait for the export function unfortunately, so I guess I'll just redo the coding. 

When importing the database (Document > Import from DNA 2.0 file..) I get the following error code:  
`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at dna.SqlConnection.getAllData(SqlConnection.java:249)
	at dna.ImportDnaDocuments.parseArticles(ImportDnaDocuments.java:394)
	at dna.ImportDnaDocuments.<init>(ImportDnaDocuments.java:179)
	at dna.Gui$MenuBar$7.actionPerformed(Gui.java:385)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by leifeld** [comment]
I've been playing with your dataset some more. I started deleting statements and documents from the end backwards and noticed that the dataset can be loaded when the statements larger than ID 115 are gone. These are statements that have a position in the text that is larger than 10,000 characters at the start. I could therefore imagine that the problem is related to the length of the documents. I'm happy to send you the document I have now after deleting statements and documents if it helps. When you redo the coding for those last few documents, I would recommend splitting the documents into smaller chunks. If it really is a problem of statement location, that should prevent the problem.

**Comment by AkselSB** [comment]
Thanks a lot! I'd be happy to have the document sent back. I'll try and do as you say and split the work into multiple databases. Could you indicate as well which documents and statements you have deleted? Thank you in advance!

**Comment by leifeld** [comment]
Will do. I deleted documents with IDs >= 8 and statements with IDs >= 115. If that was too much, you can try it successively for yourself using SQL Browser. Due to the use of foreign keys, you will first have to delete the entries corresponding to a statement ID in the DATA* tables and then in the STATEMENTS table. Only after deleting the statements with a certain document ID, you can delete the document in which the statements were contained from the DOCUMENTS table. Just to be clear: I meant splitting up the long documents into multiple smaller documents, but within the same database file.

**Comment by AkselSB** [comment]
I'll try to follow your instructions, thanks for the help!
