### ISSUE TITLE
Warning message when recoding in MySQL

### ISSUE THREAD

**Issue by TimHenrichsen** [leifeld/dna#236]
When recoding some statements in MySQL via the statement recoder, I receive the following warning message in DNA. Luckily, the statements are recoded though.

```xml
<log>
  <version>3.0.6</version>
  <date>2022-05-07</date>
  <events>
    <event>
      <date>13.05.2022 18:00:40.349</date>
      <priority>2</priority>
      <coder>1</coder>
      <summary>[SQL] Failed to retrieve statements.</summary>
      <details>Attempted to retrieve all statements from the database, but something went wrong. You should double-check if the statements are all shown!</details>
      <stackLog>logger.LogEvent&#xd;
	at gui.MainWindow$StatementTableRefreshWorker.doInBackground(MainWindow.java:1349)&#xd;
	at gui.MainWindow$StatementTableRefreshWorker.doInBackground(MainWindow.java:1132)&#xd;
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)&#xd;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xd;
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)&#xd;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)&#xd;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)&#xd;
	at java.base/java.lang.Thread.run(Thread.java:831)&#xd;
</stackLog>
      <stackException>java.sql.SQLSyntaxErrorException: Unknown column &apos;StatementId&apos; in &apos;where clause&apos;&#xd;
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)&#xd;
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)&#xd;
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)&#xd;
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)&#xd;
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)&#xd;
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)&#xd;
	at gui.MainWindow$StatementTableRefreshWorker.doInBackground(MainWindow.java:1288)&#xd;
	at gui.MainWindow$StatementTableRefreshWorker.doInBackground(MainWindow.java:1132)&#xd;
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)&#xd;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xd;
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)&#xd;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)&#xd;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)&#xd;
	at java.base/java.lang.Thread.run(Thread.java:831)&#xd;
</stackException>
    </event>
  </events>
</log>
```

**Comment by leifeld** [comment]
I think I fixed this after you last downloaded the DNA jar. Can you check with the most recent one?

**Comment by leifeld** [comment]
See commit 5a9608eba4f317fc27c125964d1e14eecb5247f7.

**Comment by leifeld** [comment]
Ah, I fixed it in one place but apparently overlooked another instance. Please find a new commit here: c48621b0b2f6732e114e88df07e2573cfd102788. Does this fix the problem?

**Comment by TimHenrichsen** [comment]
Unfortunately not. But I think it could also be related to the server somehow. Will send you an e-mail in a few minutes.

**Comment by leifeld** [comment]
Looks like something went wrong... Can you check out the most recent commit 26fbfe7e468cfb23522a5aea7832bf7121edc4b7?

**Comment by TimHenrichsen** [comment]
Yup, now it works. Thanks!
