### ISSUE TITLE
"Edit multiple statements" does not react

### ISSUE THREAD

**Issue by SofieRoehrig** [leifeld/dna#238]
In DNA 3.0.7, the function to "Edit multiple statements" does not work. After selecting multiple statements that were previously filtered, and clicking on "Edit multiple statements", DNA does not react. I had to resort to selecting and editing statements individually at the coding level

<log>
  <version>3.0.7</version>
  <date>2022-06-10</date>
  <events>
    <event>
      <date>16.06.2022 17:17:03.166</date>
      <priority>3</priority>
      <coder>1</coder>
      <summary>Uncaught exception.</summary>
      <details>An uncaught exception occurred. This is most likely a bug. Please open a new issue at https://github.com/leifeld/dna/issues/ and paste the log event stack trace and the exception stack trace there as part of your error description, along with details of what happened and under what circumstances. Thank you.</details>
      <stackLog>logger.LogEvent&#xd;
	at dna.Dna$DefaultExceptionHandler.uncaughtException(Dna.java:61)&#xd;
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1074)&#xd;
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1069)&#xd;
	at java.desktop/java.awt.EventDispatchThread.processException(EventDispatchThread.java:222)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:214)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)&#xd;
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)&#xd;
</stackLog>
      <stackException>java.lang.NullPointerException: Cannot read the array length because &quot;array&quot; is null&#xd;
	at java.base/java.util.Arrays.stream(Arrays.java:5458)&#xd;
	at java.base/java.util.stream.IntStream.of(IntStream.java:918)&#xd;
	at sql.Sql.getStatements(Sql.java:3129)&#xd;
	at gui.StatementRecoder.&lt;init&gt;(StatementRecoder.java:121)&#xd;
	at gui.MainWindow$ActionRecodeStatements.actionPerformed(MainWindow.java:2413)&#xd;
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)&#xd;
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)&#xd;
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)&#xd;
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)&#xd;
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)&#xd;
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1022)&#xd;
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1066)&#xd;
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)&#xd;
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)&#xd;
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)&#xd;
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)&#xd;
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)&#xd;
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)&#xd;
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)&#xd;
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)&#xd;
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)&#xd;
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)&#xd;
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)&#xd;
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)&#xd;
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)&#xd;
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)&#xd;
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)&#xd;
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)&#xd;
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)&#xd;
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)&#xd;
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)&#xd;
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)&#xd;
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)&#xd;
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)&#xd;
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)&#xd;
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)&#xd;
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)&#xd;
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)&#xd;
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)&#xd;
</stackException>
    </event>
  </events>
</log>

**Comment by leifeld** [comment]
Thanks, should be fixed in the latest commit. You can download a new version at https://github.com/leifeld/dna/actions as soon as the build process finishes.
