### ISSUE TITLE
Unable to export DNA database

### ISSUE THREAD

**Issue by Sukhayl** [leifeld/dna#274]
When trying to export my DNA database (I use macOS version of the software), the process becomes stuck on "Exporting network data. (2/4) Filtering statements..." 

Log stack trace:

logger.LogEvent
	at dna.Dna$DefaultExceptionHandler.uncaughtException(Dna.java:96)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1055)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1050)
	at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:1997)

Exception stack trace:

java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at org.jline.utils.InputStreamReader.<init>(InputStreamReader.java:135)
	at org.jline.utils.InfoCmp.loadDefaultInfoCmp(InfoCmp.java:612)
	at org.jline.utils.InfoCmp.lambda$static$3(InfoCmp.java:623)
	at org.jline.utils.InfoCmp.getLoadedInfoCmp(InfoCmp.java:557)
	at org.jline.terminal.impl.AbstractTerminal.parseInfoCmp(AbstractTerminal.java:209)
	at org.jline.terminal.impl.DumbTerminal.<init>(DumbTerminal.java:88)
	at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:446)
	at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:271)
	at me.tongfei.progressbar.TerminalUtils.getTerminal(TerminalUtils.java:83)
	at me.tongfei.progressbar.TerminalUtils.hasCursorMovementSupport(TerminalUtils.java:37)
	at me.tongfei.progressbar.Util.createConsoleConsumer(Util.java:34)
	at me.tongfei.progressbar.Util.createConsoleConsumer(Util.java:30)
	at me.tongfei.progressbar.ProgressBar.<init>(ProgressBar.java:79)
	at me.tongfei.progressbar.ProgressBar.<init>(ProgressBar.java:37)
	at export.Exporter.filterStatements(Exporter.java:867)
	at gui.NetworkExporter$GuiExportThread.run(NetworkExporter.java:1219)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by leifeld** [comment]
Hi there.

1. Can you please state which DNA version you are using?
2. Can you please state if you are trying to export from the `rDNA` package or from the DNA export window?
3. Does the problem occur every single time with the database you are using?
4. Does the problem occur with the sample dataset, which you can download under Releases?
5. Have you tried the same steps on a different computer with the same result?

I'd like to understand better if it is a MacOS issue or something else. Thanks for any additional details you can provide.

**Comment by Sukhayl** [comment]
Thank you for your response, Professor. Sorry for the late reply.

1. The latest one (3.0.10)
2. DNA export window
3. Yes, it does
4. No, it occurs with the dataset I have created myself
5. I will try in the next few days on a Windows computer.

**Comment by leifeld** [comment]
Have you been able to reproduce the problem also on a Windows computer?

Please feel free to send me a copy of the database by email, and I am happy to diagnose any problems with the database. You'll find my contact details [here](https://www.philipleifeld.com/contact/).

**Comment by leifeld** [comment]
Closed because no further response.

**Comment by Sukhayl** [comment]
Oh, yes, sorry about that, for some reason my response did not go through —
I was able to solve this problem by reinstalling the application.

Thanks for your help!

Best,
Sukhayl
