### ISSUE TITLE
Database export gets stuck in "4/4 Writing to file" (uncaughtException / NoSuchElementException)

### ISSUE THREAD

**Issue by mirenbz** [leifeld/dna#279]
Data export gets stuck in "Writing to file" with this settings:

![irudia](https://github.com/leifeld/dna/assets/738823/0acbcc39-ad5a-4982-bd2a-25785d8da483)

Have tried a different save location, reloading the app, rebooting the computer... nothing seems to work.

The error logs throw this message:

```
    <event>
      <date>26.06.2023 23:42:28.949</date>
      <priority>3</priority>
      <coder>1</coder>
      <summary>Uncaught exception.</summary>
      <details>An uncaught exception occurred. This is most likely a bug. Please open a new issue at https://github.com/leifeld/dna/issues/ and paste the log event stack trace and the exception stack trace there as part of your error description, along with details of what happened and under what circumstances. Thank you.</details>
      <stackLog>logger.LogEvent
			at dna.Dna$DefaultExceptionHandler.uncaughtException(Dna.java:96)
			at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1082)
			at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1077)
			at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2008)
	  </stackLog>
	  <stackException>java.util.NoSuchElementException: No value present
			at java.base/java.util.OptionalInt.getAsInt(OptionalInt.java:130)
			at export.Exporter.exportGraphml(Exporter.java:2112)
			at export.Exporter.exportToFile(Exporter.java:1891)
			at gui.NetworkExporter$GuiExportThread.run(NetworkExporter.java:1237)
			at java.base/java.lang.Thread.run(Thread.java:833)
	  </stackException>
    </event>
```

Software version is 3.0.10, 2023-03-01.

@leifeld helped narrow this down to `Variable 1` being set to `author`; it turns out that I really was after `person` here, not `author`... so this _fixes_ it for me, but might still be a problem for anyone needing to work with `author` in there.

Thanks for all the work, and the help!

**Comment by leifeld** [comment]
It took long enough, but this bug has now been fixed. The bugfix will be included in the next release at the end of this month (DNA 3.1.2). It was fixed in commit abd1cc831d01ae073bf644ac02e710ef7f15c9af. It was a problem in the visone graphml export function, which tried to look up attributes and colours for the entities; but with document-level variables, there are no attributes or colours, so it failed in those cases.
