### ISSUE TITLE
Failed to close DNA Statement Box

### ISSUE THREAD

**Issue by Affanwin** [leifeld/dna#289]
It happened when I tried to change my concept of my previous coded statements. The box appeared, I changed the concept, but when I left-click outside the box to close, it didn't close. It remained open even when this issue is being written.

logger.LogEvent
	at dna.Dna$DefaultExceptionHandler.uncaughtException(Dna.java:96)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:695)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
	at java.desktop/java.awt.EventDispatchThread.processException(EventDispatchThread.java:218)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:210)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 45
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.remove(ArrayList.java:551)
	at gui.StatementTableModel.removeStatements(StatementTableModel.java:157)
	at gui.MainWindow$13.actionPerformed(MainWindow.java:837)
[DNA Bug.png.docx](https://github.com/leifeld/dna/files/13705579/DNA.Bug.png.docx)

**Comment by leifeld** [comment]
Possible duplicate of #237 and #243. Difficult to reproduce reliably, but I've seen it a few times before, potentially with slow connections, large databases, old hardware, and/or more often when I switch window decorations on in the settings.
