### ISSUE TITLE
Unable to export dynamic visualizations (Commetrix + SoNIA)

### ISSUE THREAD

**Issue by yomlao** [leifeld/dna#42]
When trying to export dynamic networks, be that in Commetrix SQL or SoNIA format, the "Calculating" window appears and stays there, animated, forever. I have to terminate/kill the corresponding java process 'manually' using top (Ubuntu) or Task Manager (Windows). This happens with:
- Ubuntu 14.04 (using Open JDK 7 or Oracle java 7)
- Windows XP (Oracle java 7)
- Windows 7 pro (Oracle java 7)

I have the following terminal output under Ubuntu:

Exception in thread "Thread-0" java.lang.NullPointerException
    at dna.ExportWindow$FileExporter.run(ExportWindow.java:1424)
    at java.lang.Thread.run(Thread.java:745)

**Comment by leifeld** [comment]
Dynamic animations are no longer supported. Will close this legacy issue now.
