### ISSUE TITLE
delete multiple documents

### ISSUE THREAD

**Issue by ma19fr** [leifeld/dna#87]
I could not delete multiple documents (>10) at a time. If I select them and choose the option "delete selected documents", DNA deletes the statements but the documents are still existing.

**Comment by leifeld** [comment]
It works here on my end. Which version are you using? If you redirect error messages to a text file, is there any output other than the version number? Can you provide an example file?

**Comment by ma19fr** [comment]
I use the recent beta 17. 
There is no error message, DNA just deletes not all selected documents.

**Comment by leifeld** [comment]
Does it delete some of them? Or just none at all?

**Comment by ma19fr** [comment]
It deletes some of them AND all statements in the selected documents.

**Comment by leifeld** [comment]
Both in the user interface and in the database? That is, when you close the file and re-open it, are the documents still there, and the statements are still deleted?

**Comment by ma19fr** [comment]
Okay right - if I close DNA after deleting them and reopen the file, the documents are no longer listed and therefore completely deleted.

**Comment by leifeld** [comment]
OK, it looks like this is just a problem with refreshing the table. It works on my operating system, which is Linux, but sometimes there are inconsistencies between operating systems. I have now added an explicit GUI updating command after deleting the documents. I don't know if this will work on your computer, but perhaps you can try it and report back. Here is a test version: [dna-2.0-beta18-e1.zip](https://github.com/leifeld/dna/files/722235/dna-2.0-beta18-e1.zip)

Meanwhile, please also let me know which operating system and Java version you are using etc. To do so, you can redirect error messages and output to a text file in the Settings menu. Just paste a copy of the text file output here.

Note that the network export doesn't work in this test version. I am currently rewriting the export. It already contains a completely new and improved user interface for the export, but it currently doesn't do anything under the hood.

**Comment by ma19fr** [comment]
Now I used beta 18 and deleted several documents: 
- 10 documents: no problem 
- 30 documents: no problem (and no error message)

deleting more than 100 documents I got the problem, described above, and the following error message: 

DNA version: 2.0 beta 18 e1 (2017-01-22)
Java version: 1.8.0_121
Operating system: Windows 7 6.1
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 203, Size: 153
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at dna.renderer.DocumentTableModel.remove(DocumentTableModel.java:102)
	at dna.dataStructures.Data.removeDocuments(Data.java:552)
	at dna.Dna.removeDocuments(Dna.java:61)
	at dna.panels.DocumentPanel$1.actionPerformed(DocumentPanel.java:101)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by leifeld** [comment]
I tried this with the same operating system and same DNA version but a different file now, but I cannot reproduce the problem. It may be related to the order of documents or the sort order in the table.

Please download and try the following version, which disables table sorting while the documents are deleted. If this does not help, the only other option would be that you send me a copy of your file by e-mail and I'll try to reproduce the problem with that file on my computer. But try this first: [dna-2.0-beta18-e2.zip](https://github.com/leifeld/dna/files/722277/dna-2.0-beta18-e2.zip)

**Comment by ma19fr** [comment]
I tried the new version and still got the problem with >100 selected documents.

And I have sent you an e-mail with my file...

**Comment by leifeld** [comment]
Thanks. The file does not cause any problems when I delete more than 100 documents from it.

My next best guess is that this may be a speed issue. I have a pretty fast computer with an SSD, so deleting several hundred documents takes a fraction of a second. This may be considerably slower on a conventional hard disk because the database has to be accessed repeatedly.

I will look into this over the next couple of days and try to do two things:
1. try to increase the efficiency of the database access by limiting the number of times the database needs to be accessed
2. add a progress bar, so the user knows that something is happening.

I'll report back when done.

**Comment by leifeld** [comment]
I have added a simple check that reports how long it takes to delete documents. In the error output, it should show something like `GUI: 866  SQL: 828` after deleting some documents, where the first number indicates the number of milliseconds it takes to delete the documents from the user interface and the second number indicates how long it takes to delete them from the file. Can you do me a favour and try this out with some different numbers of documents and report back? E.g., with 10, 100, and 500 documents or whatever still works... This would help me to find out if the SQL code is efficient or not. I'd like to know how fast or slow it is on a normal hard disk. The above numbers 866 and 828 are reported for deleting 5,010 documents on my computer with an SSD. Here is the version that spits out the timing output: [dna-2.0-beta18-e3.zip](https://github.com/leifeld/dna/files/731292/dna-2.0-beta18-e3.zip). Thanks!

**Comment by ma19fr** [comment]
Dear Philip, 
I'm so sorry for my late answer! I tried the new beta two weeks ago and it works fine. I deleted 500 documents at once and everything worked super fast. 
Thank you!

**Comment by leifeld** [comment]
Glad it works well!
